-- replace X with a number to create as many tables as grid size

CREATE TABLE REF_TABLE_X  (
	NAME VARCHAR(32) NOT NULL,
	VAL VARCHAR(32) NOT NULL,
	constraint REF_TABLE_X_UN unique (NAME, VAL)
) ;

INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('A', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('B', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('C', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('D', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('E', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('F', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('G', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('H', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('I', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('J', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('K', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('L', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('M', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('N', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('O', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('P', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('Q', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('R', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('S', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('T', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('U', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('V', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('W', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('X', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('Y', 'u');
INSERT INTO REF_TABLE_X (NAME, VAL) VALUES ('Z', 'u');

